services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: saas_backend_prod
    environment:
      ENV_STATE: production
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      BACKEND_SECRET_KEY: ${BACKEND_SECRET_KEY}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
    ports:
      - "8000:8000"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
      target: runner
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: saas_frontend_prod
    ports:
      - "80:80"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
